services:
  automessagesender:
    build:
      context: .
      dockerfile: .dockerfile/automessagesender.Dockerfile
    container_name: automessagesender
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - POSTGRESQL_DSN=postgres://dbuser:dbpassword@postgresdb:5432/automessagesenderdb
      - WEBHOOK_SITE_URL=https://webhook.site/264d7ada-f7a7-40e9-8f30-eb0bde016436
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
  redis:
    image: redis:8
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  postgresdb:
    image: postgres:18
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      POSTGRES_DB: "automessagesenderdb"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/docker
      - ./db/schema/message_repository.sql:/docker-entrypoint-initdb.d/message_repository.sql
      - ./db/seeds/seeds01.sql:/docker-entrypoint-initdb.d/seeds01.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d automessagesenderdb" ]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  postgresdata: