services:
  automessagesender:
    build:
      context: .
      dockerfile: .dockerfile/automessagesender.Dockerfile
    container_name: automessagesender
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgresdb
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - POSTGRESQL_DSN=postgres://dbuser:dbpassword@postgresdb:5432/automessagesenderdb
  redis:
    image: redis:8
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  postgresdb:
    image: postgres:18
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      POSTGRES_DB: "automessagesenderdb"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/docker
      - ./db/schema/message_repository.sql:/docker-entrypoint-initdb.d/message_repository.sql
      - ./db/seeds/seeds01.sql:/docker-entrypoint-initdb.d/seeds01.sql
volumes:
  postgresdata: